### ISSUE TITLE
Suggestion: include extra example of how to style focused items

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk-design-system#1317]
I semi-regularly need to style custom things to have the correct focus styles. The design system sight has _almost_ what I need, but not quite.

Basically, this is the example I'm always looking for:

```scss
&:focus {
  outline: $govuk-focus-width solid $govuk-focus-colour;
}
```

I know it states each variable separately - but I'm never sure quite how I should use them. In the end I looked at the error summary sass to see the correct way.
