### ISSUE TITLE
Update width of columns in Nunjucks options table

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-design-system#2369]
## What

Adjust the width of the columns in the Nunjucks options table to allow longer names for the options.

## Why

Internationalisation work on govuk-frontend adds some pretty long option names due to pluralisation suffix (on top of the "Html" suffix used to make the translation keys). Because both the option name and type have the same width (29%), that leaves very little space for the option name, which wraps.

<img width="758" alt="Screenshot 2022-10-03 at 17 37 56" src="https://user-images.githubusercontent.com/396367/193632160-8dc77b92-e84b-4a7b-9293-4de83733e2ca.png">

## Who needs to work on this

Developers, Designers (? thinking there may be a concious decision of setting the type column to being 29% of the table, maybe not putting the type too far away from the name?)

## Who needs to review this

Developers, Designers

## Done when

- [ ] Decide on a different column width adjustment
- [ ] Implement new column width

**Comment by romaricpascal** [comment]
If that's helpful, here's a screenshot of a quick adjustment:

<img width="834" alt="Screenshot 2022-10-03 at 17 48 31" src="https://user-images.githubusercontent.com/396367/193633499-8c6ba249-b5bf-409c-ae82-e56c32e7cc1e.png">

Through some quick and dirty CSS:

```css
/* 
   Make all columns the same width so description doesn't get compressed 
   (will need some checks for older browsers)
*/
th {
  width: 100%;
}

/* Override current width set to 29% */
.app-options__limit-table-cell {
  width: 100%;
}

/* Limit type column to something smaller as it'll ever contain:
	"object", "boolean", "string" or maybe "number"/"integer" */
.app-options__limit-table-cell + .app-options__limit-table-cell {
  width: 5rem
}
```
