### ISSUE TITLE
Work out how to document different plural rules in the Nunjucks option table for the Character Count

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-design-system#2378]
Following on from a discussion in https://github.com/alphagov/govuk-frontend/issues/2895#issuecomment-1273465230:

> The documentation of the macro options hasn't been carried over yet from the first take, as I'd like to discuss the approach for it. From what I gathered, we currently have a system where we can document options as an `object`, then list the object's properties which will get extracted in the docs, like `classes` for the `formGroup` and `countMessage` options. 
> 
> <img width="904" alt="Screenshot of CharacterCount documentation showing nested options documentation for the formGroup and countMessage option" src="https://user-images.githubusercontent.com/396367/194896132-7a501200-ee6c-4e12-8606-e012cac59c36.png">
> 
> For internationalisation options, this will get very repetitive as it's [the same set of options for all the options](https://github.com/alphagov/govuk-frontend/pull/2895/files#diff-cde937e9880b3f4528adf0fe09930dfdb170736d3cb092d42173c11c00995caaR1-R14). I was thinking this is likely something that'll get described in the general documentation about configuration and internationalisation. If that's the case, it'll be lighter to just have a link pointing there rather than repeating 4 times the same list of 6 options. 
> 
> @claireashworth how does this approach sound in terms of content organisation? Would it be a problem that, unlike the other options, we'd send users off the page to let them know that for `charactersOver/UnderLimit` and wordsOver/UnderLimit` they can pass 6 possible options, depending on their language needs? 
> 
> @36degrees maybe there's another way I'm not aware to reduce duplication while documenting them on that same page, though?

We need to find a way to document how to pass different translations for different pluralization categories (`zero`, `one`, `two`, `few`, `many` or `other`) depending on the locale the Character Count is operating under, without being overly repetitive as this will apply to multiple localisable 'strings' (depending on whether the user is over or under the limit, and whether they are counting characters or words)

**Comment by 36degrees** [comment]
I don't think there's anything currently built in that would allow us to document the params in the YAML but only have them included in the Nunjucks macro options only once.

If we wanted to do the 'easiest thing' we could include the various pluralisable phrases in the YAML, document them as 'objects', but not to list the individual params in the YAML file. Instead we could put a link in the description to somewhere else (in the frontend docs?) where we can explain how they work in more detail.

Something like:

```yaml
- name: charactersOverLimitText
  type: object
  required: false
  description: Override the phrases used when the user has entered a number of characters that exceeds the limit. See [Understanding pluralisation rules](https://frontend.design-system.service.gov.uk/localising-govuk-frontend#understanding-pluralisation-rules).
- name: charactersUnderLimitText
  type: object
  required: false
  description: Override the phrases used when the user has entered a number of characters that is under the limit. See [Understanding pluralisation rules](https://frontend.design-system.service.gov.uk/localising-govuk-frontend#understanding-pluralisation-rules).
```

There's lots of reasons why this might be confusing (it's inconsistent with how we document other options with known key/value pairs, for example) but it wouldn't avoid any code changes.
